package com.paul.training.core.servlets;

import java.io.IOException;

import javax.servlet.ServletException;

import org.apache.felix.scr.annotations.sling.SlingServlet;
import org.apache.sling.api.SlingHttpServletRequest;
import org.apache.sling.api.SlingHttpServletResponse;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.api.servlets.SlingSafeMethodsServlet;

/**
 * Servlet that writes some sample content into the response. It is mounted for all resources of a
 * specific Sling resource type. The {@link SlingSafeMethodsServlet} shall be used for HTTP methods
 * that are idempotent. For write operations use the SlingAllMethodsServlet.
 */
@SuppressWarnings("serial")
@SlingServlet(resourceTypes = "paul/structure/page")
public class SimpleServlet extends SlingSafeMethodsServlet {

    @Override
    protected void doGet(final SlingHttpServletRequest req,
                         final SlingHttpServletResponse resp) throws ServletException, IOException {
        final Resource resource = req.getResource();
        resp.getOutputStream().println(resource.toString());
        resp.getOutputStream().println(
                "This content is generated by the SimpleServlet");
    }
}
